# Generated by Django 5.0.7 on 2024-08-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='end_date',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='user',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='start_date',
            new_name='startDate',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='status',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='subscription',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='subscription',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subscription',
            name='surname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
