# Generated by Django 5.0.7 on 2024-08-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_rename_end_date_subscription_enddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
